### ISSUE TITLE
[iOS] Setup project app flavors

### ISSUE THREAD

**Issue by luongvo** [nimblehq/kmm-templates#10]
## Why

We must prepare 2 app build flavors: staging and production for the iOS app. These app build flavors help us to config and distribute corresponding apps on each staging & production API environment.

## Acceptance Criteria

- Set up project app flavors: `staging` and `production`.
- Set up app names.
- Set up app icons.

**Comment by phongvhd93** [comment]
The iOS template already have pre-installed schemes for Staging and Production
