### ISSUE TITLE
Setup buildSrc to manage dependencies in project

### ISSUE THREAD

**Issue by phongvhd93** [nimblehq/kmm-templates#22]
## Why

To make it easier to maintain and update the plugins and dependencies used in the project, we need to create the `buildSrc` folder.

## Acceptance Criteria

- The buildSrc must sit in the root project directory.
- All of the dependencies and plugins used in the application must be defined in `buildSrc`

## Resource
- [Documentation](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources)
- Example: [Avishek-Phong-KMM-IC](https://github.com/nimblehq/avishek-phong-kmm-ic)

**Comment by luongvo** [comment]
@phongvhd93 @AVI5HEK This has been resolved in this PR https://github.com/nimblehq/kmm-templates/pull/26 👋
