### ISSUE TITLE
Setup build env config & networking layer

### ISSUE THREAD

**Issue by luongvo** [nimblehq/kmm-templates#8]
## Why

Before having more backend tasks on some screens, we must set up the networking layer in the shared KMM module. 

## Acceptance Criteria

- Provide corresponding env variables for each platform (Android & iOS) and each env (staging & production) by using [BuildKonfig](https://github.com/yshrsmz/BuildKonfig). For example:
  - SECRET
  - BASE_URL

- Wrap around [Ktor](https://ktor.io/docs/getting-started-ktor-client-multiplatform-mobile.html) library.
- Show request log.

**Comment by AVI5HEK** [comment]
@kaungkhantsoe has already added BuildKonfig and Ktor in [this](https://github.com/nimblehq/kmm-templates/tree/feature/13-part-2-implement-ktor-and-backend-tasks) branch for the 2nd part of #13 . I should archive this issue. @luongvo

**Comment by luongvo** [comment]
cc @phongvhd93

**Comment by phongvhd93** [comment]
Close due to already implemented in #13
